version: '3'

services:

  broker-service:
    container_name: broker
    build:
      context: broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "127.0.0.1:8080:8080/tcp"
    deploy:
      mode: replicated
      replicas: 1
      
  authentication-service:
    container_name: auth
    build:
      context: authentication-service
      dockerfile: authentication-service.dockerfile
    restart: always
    ports:
      - "127.0.0.1:8081:8080/tcp"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
  
  postgres:
    container_name: postgres
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/ 
