version: '3'

services:

  broker-service:
    build:
      context: broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:8001"
    deploy:
      mode: replicated
      replicas: 1
